spring:
  datasource:
    url: jdbc:mysql://192.168.2.146:3306/tjs_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&failOverReadOnly=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    sql-injector=com:
      baomidou:
        mybatisplus:
          mapper:
            LogicSqlInjector
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
